### PR TITLE
Install GAP documentation

### LINKED ISSUE #70: Package does not contain documentation
Currently we drop all documentation because that's what SageMath used to do at some point (and we used their build script as a starting point it seems.)

We should probably install the documentation with `gap` but not with `gap-core` or something like that. (PRs welcome.)

### PR DESCRIPTION
**Pull request by fingolfin**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Resolves #70

### CODE REVIEW

**Comment by fingolfin** [comment]
Since the size of the manual was mentioned before: if that's a concern, it would be good to know what the rules are resp. what is acceptable and what not.

Regarding "users won't know where to find the documentation": many users known about the GAP user preference `HelpViewers` which can be changed to display the help via a HTML or PDF viewer. These users do not need know the file locations, GAP knows them.

**Comment by isuruf** [comment]
We can try this and move the docs to a separate package if the size becomes a problem

**Comment by isuruf** [comment]
Thanks

**Comment by fingolfin** [comment]
Out of genuine curiosity, in which way might the size become a problem? Are there some hard coded limits in the Conda software stack the limit the size of a package? I would have thought that there are software packages considerably larger than GAP, but thinking about this again now I admit all examples that come to mind are commercial (such as Mathematica).
Or is it more a concern that some users might complain why Conda uses so much disk space? 
Or something else?

Anyway, if you need to reduce the size, I would recommend to first and only delete the PDFs, as they add to quite a bit, and it is fairly easy to just remove them (just remove all files with extension `.pdf` inside the GAP tree)

**Comment by isuruf** [comment]
>  Or is it more a concern that some users might complain why Conda uses so much disk space?

This one. For eg: the sage installation is quite large and takes a while to download and gap package getting bigger will add to the time to download and install sage.

**Pull request merged**
