### PR TITLE
Add nq package

### PR DESCRIPTION
**Pull request by enriqueartal**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

New PR, for adding nq, former one was messed up

### CODE REVIEW

**Comment by isuruf** [comment]
`nq` package is in `gap` package. Please open an issue if that doesn't work.

**Comment by enriqueartal** [comment]
This is to be usted in sage. Should sage or sagelib be modified replacing gap-defaults by gap?

**Comment by isuruf** [comment]
No, a user can install both `sage` and `gap`.

**Comment by enriqueartal** [comment]
And then which `gap` will `sage` use?

**Comment by isuruf** [comment]
It's the same gap with `nq` package installed as well.

**Comment by enriqueartal** [comment]
It works, `sage` finds the package `nq`. I put `gap` before `sage=9.6`; I had also a gap jupyter notebook but the gap kernel did not work (minor issue). Thanks, Enrique.

**Pull request closed without merging**
